export const PathURL = {
  Management: "",
  Dashboard: "/dashboard",
  Login: "/login",
  Logout: "/logout",
  NotFound: "/404",
  Forbidden: "/403",
  Transaction: "/transaction",
  TransactionDetail: "/transaction/detail/:id",
  ServicePackage: "/service-package",
  Profile: "/profile",
  Facebook: "/facebook",
  Tiktok: "/tiktok",
  Instagram: "/instagram",
  Lazada: "/lazada",
  Youtube: "/youtube",
  Shopee: "/shopee",
  AutoFarmer: "/auto-farmer",
  Agency: "/agency",
  Orders: "/orders",
  Comments: "/comments",
  Giftcode: "/giftcode",
  Download: "/download",
  DocumentAPI: "/documentapi"
};
