export const RouterName = {
  Root: "Root",
  Management: "Management",
  Dashboard: "Dashboard",
  Clone: "Clone",
  Login: "Login",
  Logout: "Logout",
  NotFound: "404NotFound",
  Forbidden: "403Forbidden",
  Transaction: "Transaction",
  TransactionDetail: "TransactionDetail",
  ServicePackage: "ServicePackage",
  Profile: "Profile",
  Facebook: "Facebook",
  Tiktok: "Tiktok",
  Instagram: "Instagram",
  Lazada: "Lazada",
  Youtube: "Youtube",
  Shopee: "Shopee",
  AutoFarmer: "AutoFarmer",
  Agency: "Agency",
  Orders: "Orders",
  Comments: "Comments",
  Giftcode: "Giftcode",
  Download: "Download",
  DocumentAPI: "DocumentAPI"
};
